# Generated by Django 5.1.4 on 2025-01-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kursy_online", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="avatar.png", null=True, upload_to=""),
        ),
    ]
