# Generated by Django 5.1.4 on 2025-01-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kursy_online", "0003_user_activation_token_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
