# Generated by Django 5.1.4 on 2025-01-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kursy_online", "0006_user_rating_average_teacherrating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="rating_average",
            new_name="teacher_rating_average",
        ),
    ]
