# Generated by Django 5.1.4 on 2025-01-29 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kursy_online", "0007_rename_rating_average_user_teacher_rating_average"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherrating",
            name="created_at",
        ),
        migrations.AddField(
            model_name="teacherrating",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacherrating",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kursy_online.course"
            ),
        ),
        migrations.AlterField(
            model_name="teacherrating",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="teacherrating",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
